# -*- coding: utf-8 -*-
"""lab3_422.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3bnVXqszZkbVbP-Q5eedLJaez55I7QO
"""

import random
import math
def strength (s):
    return math.log2(x+1)+x/10

def utility(maxV,minV,i):
    i= random.radient(0,1)
    random_v= random.radient(1,10)
    return strength(maxV) - strength(minV) + ((-1) ** i) * (rand_val / 10)

def alpha_beta_minmax(depth,is_max,alpha,beta,maxV,minV):
    if depth == 0:
        s = random.radient(0,1)
        return utility(maxV,minV,s)
        if is_max == True:
            maxpoint = float("-inf")
            for i in range (0,2,1):
                val = alpha_beta_minmax(depth-1,False,alpha,beta,maxV,minV)
                maxpoint = max(maxpoint,val)
                alpha = max(alpha,val)
                if beta <= alpha:
                    break
            return maxpoint
        else:
            minpoint = float("inf")
            for i in range (0,2,1):
                val = alpha_beta_minmax(depth-1,True,alpha,beta,maxV,minV)
                minpoint = min(minpoint,val)
                beta = min(beta,val)
                if beta <= alpha:
                    break
            return minpoint
def game_function(starting,maxV,minV):
    if starting == 0:
        winner_v = alpha_beta_minmax(5,True,float("-inf"),float("inf"),maxV,minV)
        if winner_v > 0:
            winner = 'Magnus Carlsen (Max)'
        elif winner_v == 0:
            winner = 'Draw'
        else:
            winner = 'Fabiano Caruana (Min)'

    else:
        winner_v = alpha_beta_minmax(5,False,float("-inf"),float("inf"),maxV,minV)
        if winner_v > 0:
            winner = 'Fabiano Caruana (Max)'
        elif winner_v == 0:
            winner = 'Draw'
        else:
            winner = 'Magnus Carlsen (Min)'
    return winner

#driver code
result = []
draw = 0
carlsen = 0
caruana = 0
starting = int(input("Enter starting player for game-1 [0 for Magnus Carlsen, 1 for Fabiano Caruana]: "))
maxV = float(input("Enter base strength for Magnus Carlsen: "))
minV = float(input('Enter base strength for Fabiano Caruana: '))
for game in range (0,4,1):
    if game%2 == 0:
        win_v,winner = game_function(starting,maxV,minV)
    else:
        win_v,winner = game_function(1-starting,maxV,minV)
    temp = [win_v,winner]
    result.append(temp)
    if winner == 'Draw':
        draw += 1
    elif winner == 'Magnus Carlsen (Max)':
        carlsen += 1
    else:
        caruana += 1
    print(f"Game {game+1} Winner: {winner} (utility value:{round(win_v,2)})")

print("Overall Results:")
print(f"Magnus Carlsen wins: {carlsen_wins}")
print(f"Fabiano Caruana wins: {caruana_wins}")
print(f"Draws: {draw}")
print()
if carlsen_wins > caruana_wins:
    print("Overall Winner: Magnus Carlsen")
elif caruana_wins > carlsen_wins:
    print('Overall Winner: Fabiano Caruana')
else:
    print('Overall Winner: Draw')